#Requires -Version 7.2

$private = @(Get-ChildItem -Path (Join-Path $PSScriptRoot 'Private') -Filter '*.ps1' -ErrorAction SilentlyContinue)
$public = @(Get-ChildItem -Path (Join-Path $PSScriptRoot 'Public') -Filter '*.ps1' -ErrorAction SilentlyContinue)

foreach ($file in @($private + $public)) {
    . $file.FullName
}

Export-ModuleMember -Function @(
    'Get-HmdConfig'
    'Resolve-HmdApiKey'
    'Get-HmdDefaultApiKeyCredentialTarget'
    'Get-HmdApiKeyFromCredentialManager'
    'Set-HmdApiKeyCredential'
    'Remove-HmdApiKeyCredential'
    'ConvertTo-HmdFlatArray'
    'Get-HmdProgressPercent'
    'Format-HmdProgressLine'
    'New-HmdProgressContext'
    'Write-HmdProgress'
    'Import-HmdUrlList'
    'Initialize-HmdWorkRoot'
    'Get-HmdUrlLeafName'
    'Get-HmdSafeFileName'
    'Get-HmdDeployMatchKeys'
    'Test-HmdHttpUrl'
    'Get-HmdUrlsFromDeployMap'
    'Invoke-HmdLocalAvScan'
    'Get-HmdFileSha256'
    'Test-HmdCacheEntryFresh'
    'Import-HmdHashCache'
    'Export-HmdHashCache'
    'Get-HmdVerdictFromStats'
    'Get-HmdIgnoreEngineList'
    'Get-HmdPolicyStatsFromResults'
    'Import-HmdCheckpoint'
    'Save-HmdCheckpoint'
    'Invoke-HmdRest'
    'Get-HmdHashReport'
    'Submit-HmdFile'
    'Get-HmdAnalysis'
    'Start-HmdDownloadPool'
    'Get-HmdAuthenticodeInfo'
    'Move-HmdByVerdict'
    'New-HmdHtmlReport'
    'Import-HmdDeployMap'
    'Copy-HmdCleanDeploy'
    'Test-HmdDeployPatternIsGlob'
    'Get-HmdDefaultArchiveExtensions'
    'Get-HmdDefaultArchiveInterestingExtensions'
    'Get-HmdDefaultArchiveInterestPathKeywords'
    'Resolve-HmdArchiveVtMode'
    'Get-HmdArchiveMemberInterest'
    'Test-HmdIsArchivePath'
    'Test-HmdIsArchiveScanRow'
    'ConvertTo-HmdScanLogRow'
    'Import-HmdScanLogCsv'
    'Export-HmdScanLogCsv'
    'Get-HmdMergedVerdict'
    'Expand-HmdArchiveSafe'
    'Invoke-HmdArchiveInspect'
    'Get-HmdInboxPaths'
    'Initialize-HmdInbox'
    'Test-HmdInboxInputFileName'
    'Get-HmdInboxDeployMapPath'
    'Get-HmdInboxNextJob'
    'Move-HmdInboxJob'
    'Enter-HmdInboxMutex'
    'Exit-HmdInboxMutex'
    'Invoke-HmdInboxWorker'
    'Invoke-HmdBulkDownload'
)
