@{
    RootModule        = 'Hash.MassDownloader.psm1'
    ModuleVersion     = '0.7.0'
    GUID              = 'c8e4a1b2-7f3d-4a9e-b5c1-0d8e2f6a4b19'
    Author            = 'Ville Pispa'
    CompanyName       = 'Independent'
    Copyright         = '(c) 2026 Ville Pispa. MIT License.'
    Description       = 'Bulk URL downloader with SHA256-first hash reputation (VirusTotal-first), cache, quarantine, and HTML reports.'
    PowerShellVersion = '7.2'
    FunctionsToExport = @(
        'Get-HmdConfig'
        'Resolve-HmdApiKey'
        'Get-HmdDefaultApiKeyCredentialTarget'
        'Get-HmdApiKeyFromCredentialManager'
        'Set-HmdApiKeyCredential'
        'Remove-HmdApiKeyCredential'
        'ConvertTo-HmdFlatArray'
        'Get-HmdProgressPercent'
        'Format-HmdProgressLine'
        'New-HmdProgressContext'
        'Write-HmdProgress'
        'Import-HmdUrlList'
        'Initialize-HmdWorkRoot'
        'Get-HmdUrlLeafName'
        'Get-HmdSafeFileName'
        'Get-HmdDeployMatchKeys'
        'Test-HmdHttpUrl'
        'Get-HmdUrlsFromDeployMap'
        'Invoke-HmdLocalAvScan'
        'Get-HmdFileSha256'
        'Test-HmdCacheEntryFresh'
        'Import-HmdHashCache'
        'Export-HmdHashCache'
        'Get-HmdVerdictFromStats'
        'Get-HmdIgnoreEngineList'
        'Get-HmdPolicyStatsFromResults'
        'Import-HmdCheckpoint'
        'Save-HmdCheckpoint'
        'Invoke-HmdRest'
        'Get-HmdHashReport'
        'Submit-HmdFile'
        'Get-HmdAnalysis'
        'Start-HmdDownloadPool'
        'Get-HmdAuthenticodeInfo'
        'Move-HmdByVerdict'
        'New-HmdHtmlReport'
        'Import-HmdDeployMap'
        'Copy-HmdCleanDeploy'
        'Test-HmdDeployPatternIsGlob'
        'Get-HmdDefaultArchiveExtensions'
        'Get-HmdDefaultArchiveInterestingExtensions'
        'Get-HmdDefaultArchiveInterestPathKeywords'
        'Resolve-HmdArchiveVtMode'
        'Get-HmdArchiveMemberInterest'
        'Test-HmdIsArchivePath'
        'Test-HmdIsArchiveScanRow'
        'ConvertTo-HmdScanLogRow'
        'Import-HmdScanLogCsv'
        'Export-HmdScanLogCsv'
        'Get-HmdMergedVerdict'
        'Expand-HmdArchiveSafe'
        'Invoke-HmdArchiveInspect'
        'Get-HmdInboxPaths'
        'Initialize-HmdInbox'
        'Test-HmdInboxInputFileName'
        'Get-HmdInboxDeployMapPath'
        'Get-HmdInboxNextJob'
        'Move-HmdInboxJob'
        'Enter-HmdInboxMutex'
        'Exit-HmdInboxMutex'
        'Invoke-HmdInboxWorker'
        'Invoke-HmdBulkDownload'
    )
    PrivateData       = @{
        PSData = @{
            Tags         = @('Hash', 'Reputation', 'VirusTotal', 'Malware', 'Download', 'Security', 'PowerShell')
            LicenseUri   = 'https://opensource.org/licenses/MIT'
            ProjectUri   = 'https://github.com/villepispa/hash-mass-downloader'
            ReleaseNotes = 'v0.7.0 — input-line trim (HMD-049) and VirusTotal release URL scan (HMD-048).'
        }
    }
}
